### ISSUE TITLE
Implement CodeDeploy.GetDeploymentOutput to monitor and verify the deployment

### ISSUE THREAD

**Issue by mstepanyak** [SharpeRAD/Cake.AWS.CodeDeploy#3]
There is no possibility to Monitor and Verify the Deployment

**Comment by SharpeRAD** [comment]
I’m not really sure what your expectations are with this issue? Please submit a PR for any additional features.

**Comment by OrangeTimes** [comment]
I think the issue is that Code Deploy task returns result immediately without waiting for CodeDeploy to finish on AWS

**Comment by SharpeRAD** [comment]
I think you’ll need to create the deployment then periodically query it until the status changes. Submit a PR for an alias that gets the DeploymentInfo using the id that was returned from the create alias.

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CodeDeploy/MICodeDeployGetDeploymentGetDeploymentRequest.html

**Comment by SharpeRAD** [comment]
I added a GetDeploymentInfo method in v0.1.7 that you could choose to call periodically until the status changes
